### ISSUE TITLE
Remove application specific documents on delete application event.

### ISSUE THREAD

**Issue by yanivmn** [aerobase/unifiedpush-server#16]

**Comment by yaniv-cb4** [comment]
According to several posts, selected implementation will manually denormalize user_id.

`create table if not exists documentd_user_id (push_application_id uuid, database text, user_id text, snapshot timeuuid, PRIMARY KEY (push_application_id, database, user_id));
`
1) http://www.datastax.com/dev/blog/materialized-view-performance-in-cassandra-3-x
Manual denormalization becomes faster is a few hundred rows per partition.

2) https://docs.datastax.com/en/cql/3.3/cql/cql_using/useSecondaryIndex.html
https://docs.datastax.com/en/cql/3.3/cql/cql_using/useSecondaryIndex.html

3) https://docs.datastax.com/en/cql/3.3/cql/cql_using/useWhenIndex.html#useWhenIndex__when-no-index

4) Future improvement might exists with a combination of index and a static column.
