### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by choxxy** [aerobase/unifiedpush-server#36]
Hi, how do I use my own certificates instead of the generated certs?

**Comment by yanivmn** [comment]
Assuming you are using omnibus installer, you can follow [this guide](https://github.com/aerobase/omnibus-unifiedpush-server/blob/master/doc/settings/nginx.md) 

> Because the hostname in our example is 'aerobase.example.com', aerobase will look for key and certificate files called /etc/unifiedpush/ssl/aerobase.example.com.key and /etc/unifiedpush/ssl/aerobase.example.com.crt, respectively. Create the /etc/unifiedpush/ssl directory and copy your key and certificate there.

`
sudo mkdir -p /etc/unifiedpush/ssl;
sudo chmod 700 /etc/unifiedpush/ssl;
sudo cp aerobase.example.com.key aerobase.example.com.crt /etc/unifiedpush/ssl/
`

**Comment by choxxy** [comment]
I wasn't using the omnibus, am trying omnibus  but i get this error
* ruby_block[wait for cassandra to start] action runnodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.
[2018-02-13T15:15:58+00:00] FATAL: Could not connect to local cassandra node, retrying in 10 seconds.
[2018-02-13T15:15:58+00:00] FATAL: Could not connect to local cassandra node, retrying in 10 seconds.
and it won't work. This is after downloading version 1.2.0 stable and install in ubuntu 16.04

**Comment by yanivmn** [comment]
This might be the case when hostname is not properly set to your machine.
Please verify hostname resolved to the same address used in /etc/unifiedpush/unifiedpush.rb

In addition please attache /var/opt/unifiedpush/cassandra/cassandra/logs/system.log to this issue

**Comment by choxxy** [comment]
Here is the log file
[system.log](https://github.com/aerobase/unifiedpush-server/files/1721027/system.log)

**Comment by yanivmn** [comment]
This is a known issue when hostname doesn't resolve to the right ip.

1) Add host file entry to /etc/hosts 
192.168.100.10 YOUR_HOST_NAME (YOUR_HOST_NAME -> output from hostname command).
2) Stop all services `sudo unifiedpush-ctl stop `
3) Reconfigure  `sudo unifiedpush-ctl reconfigure`
4) Start `sudo unifiedpush-ctl start`

**Comment by choxxy** [comment]
Thanks, it worked. but I had to restart my machine
