### ISSUE TITLE
Cassandra use

### ISSUE THREAD

**Issue by choxxy** [aerobase/unifiedpush-server#39]
Can I disable it ? and will it impact my server performance ? am trying to minimise processes running on my machine

**Comment by yanivmn** [comment]
Theoretically cassaandra is required only when using database / documents REST API.
For Push Notification and IDP/IDM only PostgreSQL is required.

However, disabling cassandra without linking to an external cluster will lead to startup errors.

> '#' cassandra['enable'] = true

> cassandra['enable'] = false

Please open an issue request, at [https://aerobase.atlassian.net](https://aerobase.atlassian.net)

> Support server startup when cassandra is down

**Comment by choxxy** [comment]
Ok cool I will stop cassandra after startup till this issue is resolved.
