### ISSUE TITLE
aerobase-ctl reconfigure

### ISSUE THREAD

**Issue by henrynewman** [aerobase/unifiedpush-server#44]
Good day I'm trying to install Aerobase in a cloud-based Ubuntu VM. When I get to the` aerobase-ctl reconfigure` to stage it says I must accept to continue. The problem is only able to view the Apache license but not accept. Any suggestions?

**Comment by yanivmn** [comment]
Try adding  --accept-license to reconfigure command

**Comment by henrynewman** [comment]
Worked like a charm. Thank you for the assist @yanivmn 

Can someone update this in the docs.
